// <auto-generated />
namespace Books.Web.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DefaultSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DefaultSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201507091709436_DefaultSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
